# Generated by Django 3.2.7 on 2021-09-06 18:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('JcBBS', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article_msg',
            options={'verbose_name': '帖子信息表', 'verbose_name_plural': '帖子信息表'},
        ),
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': '帖子主表', 'verbose_name_plural': '帖子主表'},
        ),
        migrations.AlterModelOptions(
            name='articles_type',
            options={'verbose_name': '信息类型', 'verbose_name_plural': '信息类型'},
        ),
        migrations.AlterModelOptions(
            name='block',
            options={'verbose_name': '城市区', 'verbose_name_plural': '城市区'},
        ),
        migrations.AlterModelOptions(
            name='cities',
            options={'verbose_name': '城市表', 'verbose_name_plural': '城市表'},
        ),
        migrations.AlterModelOptions(
            name='nymph_photo',
            options={'verbose_name': '照片表', 'verbose_name_plural': '照片表'},
        ),
        migrations.AlterModelOptions(
            name='nymph_price',
            options={'verbose_name': '价格表', 'verbose_name_plural': '价格表'},
        ),
        migrations.AlterModelOptions(
            name='provinces',
            options={'verbose_name': '省份表', 'verbose_name_plural': '省份表'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': '用户表', 'verbose_name_plural': '用户表'},
        ),
        migrations.AddField(
            model_name='nymph_photo',
            name='update_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='修改时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article_msg',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='JcBBS.articles', verbose_name='帖子id'),
        ),
        migrations.AlterField(
            model_name='article_msg',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='article_msg',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='article_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JcBBS.articles_type', verbose_name='帖子类型'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JcBBS.block', verbose_name='城市-区id'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JcBBS.users', verbose_name='用户id'),
        ),
        migrations.AlterField(
            model_name='articles_type',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='articles_type',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='block',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JcBBS.cities', verbose_name='城市id'),
        ),
        migrations.AlterField(
            model_name='block',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='block',
            name='name',
            field=models.CharField(max_length=32, verbose_name='城市-区'),
        ),
        migrations.AlterField(
            model_name='block',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='cities',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='cities',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JcBBS.provinces', verbose_name='省份id'),
        ),
        migrations.AlterField(
            model_name='cities',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='nymph_photo',
            name='article_msg',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='JcBBS.article_msg', verbose_name='帖子详情id'),
        ),
        migrations.AlterField(
            model_name='nymph_photo',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='nymph_price',
            name='article_msg',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='JcBBS.article_msg', verbose_name='帖子详情id'),
        ),
        migrations.AlterField(
            model_name='nymph_price',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='nymph_price',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='provinces',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='provinces',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='users',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='users',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
    ]
