# Generated by Django 3.2.3 on 2021-05-20 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JcBBS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles_type',
            name='types',
            field=models.CharField(choices=[('lf', '楼凤'), ('xy', '洗浴'), ('zy', '足浴'), ('zj', '站街'), ('qq', 'QQ'), ('hd', '黑店'), ('ktv', 'KTV')], max_length=8, verbose_name='类型'),
        ),
    ]
