# Generated by Django 3.2 on 2021-05-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JcBBS', '0002_alter_articles_type_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='cities',
            name='is_ftc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='provinces',
            name='is_ftc',
            field=models.IntegerField(default=0),
        ),
    ]
